FROM postgres:12

LABEL maintainer="PostGIS Project - https://postgis.net"

ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.0.3+dfsg-2.pgdg100+1

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-12-postgis-3 postgresql-12-postgis-3-scripts postgresql-server-dev-12 postgis \
      && rm -rf /var/lib/apt/lists/*



RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    pgxnclient

# Install H3 C Library
RUN pgxn install h3

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh
COPY ./update-postgis.sh /usr/local/bin

EXPOSE 5432